# Generated by Django 5.0.1 on 2024-02-08 18:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccounts',
            fields=[
                ('name', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('use_tls', models.BooleanField(default=True)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('default_sender', models.EmailField(max_length=254)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
