# Generated by Django 5.0.1 on 2024-02-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_monitor_app', '0003_emailaccounts_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ERROR', 'Error'), ('INFO', 'Info'), ('WARNING', 'Warning')], max_length=10)),
                ('log_type', models.CharField(choices=[('SCHEDULER', 'Scheduler Job'), ('EMAIL_QUEUE', 'Email Queue'), ('NOTIFICATION', 'Notification')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
