# Generated by Django 5.0.3 on 2024-03-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_monitor_app', '0004_serverlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccounts',
            name='default_sender',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccounts',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccounts',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccounts',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccounts',
            name='use_tls',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccounts',
            name='username',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
